### ISSUE TITLE
No matching service worker detected

### ISSUE THREAD

**Issue by borisdiakur** [khalyomede/gridsome-plugin-manifest#3]
<img width="966" alt="Screen Shot 2020-02-12 at 14 41 55" src="https://user-images.githubusercontent.com/527049/74340284-ec711d00-4da5-11ea-9893-91b921735a8c.png">

In gridsome.config.js

```js
plugins: [
    {
      use: 'gridsome-plugin-manifest',
      options: {
        background_color: '#000000',
        icon_path: './src/assets/images/icon.png',
        name: 'Foobar',
        short_name: 'Yolo',
        theme_color: '#FFFFFF',
        lang: 'en',
      },
    },
```

Any idea?

**Comment by khalyomede** [comment]
Hi there, I this is absoluetly normal because this plug-in only manages generating a manifest.json file.

If you want to generate a service worker, you can use either plugins:

- [gridsome-plugin-pwa](https://github.com/rishabh3112/gridsome-plugin-pwa)
- [gridsome-plugin-service-worker](https://github.com/khalyomede/gridsome-plug-in-service-worker)

Let me know if you feel this does not solve your issue, or if you need any guidance 😉
