### ISSUE TITLE
Error: Input file contains unsupported image format

### ISSUE THREAD

**Issue by Kulcanhez** [khalyomede/gridsome-plugin-manifest#6]
Hello @khalyomede! Thank you for this amazing plugin 🚀

I was trying to use it for the first time but I have this error: `Error: Input file contains unsupported image format`. My icon is in the root of the src folder `icon_path: './src/favicon.png'`.

I thought that was maybe due to some file format bug so I opened Photoshop and resaved but the problem remains.

Do you have any idea of what is causing this?

Thank you very much!!!!

**Comment by vergissberlin** [comment]
💁‍♂️  I have the same problem.

**Comment by vergissberlin** [comment]
I've found out the instead of sharp 0.25.0, sharp version 0.23.4 is installed. 
During the installation I get the following warning:
`warning " > gridsome-plugin-manifest@0.3.4" has unmet peer dependency "sharp@0.25.x".`

Updating sharp helped me out:
```bash
rm -rf node_modules/sharp/vendor
yarn add -D sharp@0.25
```

I will send a  suitable pull request for.

kind regards,
André

**Comment by vergissberlin** [comment]
🗒️ I have to add the notice, that sharp 0.25.0 is not compatible with node v10.

**Comment by khalyomede** [comment]
Thank you both for the time you spent to report and figure out the issue, you all rocks :)

The issue should be fixed if you upgrade to version `gridsome-plugin-manifest@0.3.5` for now.

If you encounter any issue, please feel free to reopen this issue guys! Have a safe week.
